// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7UmY_RTiZOjU9RSSJnfmIWMeiNrw1kCM',
    appId: '1:960610492652:android:b8bee2c5de01ae9e8d05c9',
    messagingSenderId: '960610492652',
    projectId: 'strengthchronicle',
    storageBucket: 'strengthchronicle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSxjd_zjy55RzC3Hvet1Q3wHfizfgLDTg',
    appId: '1:960610492652:ios:5d9737c8ec29450e8d05c9',
    messagingSenderId: '960610492652',
    projectId: 'strengthchronicle',
    storageBucket: 'strengthchronicle.appspot.com',
    androidClientId: '960610492652-9b0284ume6urgbv08e0h4mm19au718a3.apps.googleusercontent.com',
    iosClientId: '960610492652-rif0n3ao8cj5mhnut1849fovjbdsd583.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutApp',
  );
}
